### ISSUE TITLE
tablas de verdad y cocodrile

### ISSUE THREAD

**Issue by Irwingferia** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-team-sael-1as#1]
[TABLAS DE VERDAD Y COCODRILE.pdf](https://github.com/user-attachments/files/17483775/TABLAS.DE.VERDAD.Y.COCODRILE.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
